# Generated by Django 4.2.1 on 2023-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='I really like this course', max_length=1000),
            preserve_default=False,
        ),
    ]
