# Generated by Django 4.2.1 on 2023-06-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='course',
        ),
        migrations.CreateModel(
            name='HoleDisplay',
            fields=[
                ('hole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rounds.hole')),
                ('yardage', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.course')),
            ],
            bases=('rounds.hole',),
        ),
    ]
