# Generated by Django 4.2.2 on 2023-06-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holedisplay',
            name='yardage',
        ),
        migrations.AddField(
            model_name='hole',
            name='yardage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
